version: '3.8'

services:
  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    env_file: .env
    volumes:
      - ./src:/app/apps/src
    ports:
      - ${USERS_PORT}:${USERS_PORT}
    depends_on:
      - db
      - msgBroker
  db:
    image: mongo:latest
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
  msgBroker:
    image: rabbitmq:4-management-alpine
    env_file: .env
    ports:
      - ${MSG_BROKER_PORT}:${MSG_BROKER_PORT}
      - 15672:15672