version: '3.8'

services:
  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    command: sh -c "until nc -z msgBroker 5672; do echo 'Waiting for RabbitMQ...'; sleep 2; done && node main"
    env_file: .env
    volumes:
      - ./src:/app/apps/src
    ports:
      - ${USERS_PORT}:${USERS_PORT}
    depends_on:
      - db
      - msgBroker
  
  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
    command: sh -c "until nc -z msgBroker 5672; do echo 'Waiting for RabbitMQ...'; sleep 2; done && node main"
    env_file: .env
    volumes:
      - ./src:/app/apps/src
    depends_on:
      - msgBroker
  db:
    image: mongo:latest
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}
  msgBroker:
    image: rabbitmq:4-management-alpine
    env_file: .env
    ports:
      - ${MSG_BROKER_PORT}:${MSG_BROKER_PORT}
      - 15672:15672