version: '3.8'

services:
  users:
    build:
      context: .
      dockerfile: apps/users/Dockerfile
    env_file: .env
    volumes:
      - ./src:/app/apps/src
    ports:
      - ${USERS_PORT}:${USERS_PORT}
  db:
    image: mongo:latest
    env_file: .env
    ports:
      - ${DB_PORT}:${DB_PORT}